Repository MSFS-Mega-Pack/MSFS2020-livery-manager, pull requests merged in 2020-10, with the labels that each got.

#75 WIP: add working auto-update
  .github/workflows/node.js.yml
  .github/workflows/release.yml
  .gitignore
  package.json
  src/components/App.js
  src/components/ContributorBadge.js
  src/components/ErrorDialog.js
  src/components/HomeTabs/AvailableLiveries/AircraftAccordion.js
  src/components/HomeTabs/AvailableLiveries/AvailableLiveries.js
  src/components/HomeTabs/AvailableLiveries/FullTable.js
  src/components/HomeTabs/AvailableLiveries/ListRow.js
  src/components/HomeTabs/AvailableLiveries/LiveryList.js
  src/components/HomeTabs/InstalledLiveries/InstalledLiveries.js
  src/components/HomeTabs/Settings.js
  src/components/Loading.js
  src/components/MainPage.js
  src/components/RefreshBox.js
  src/data/Constants.json
  src/data/PlaneNameTable.json
  src/images/no-image-available.pdn
  src/images/no-image-available.png
  src/index.js
  src/pages/HomePage.js
  update-available.html
  updater.js
  webpack.build.config.js
  yarn.lock
Labels: area: setup, type: backend

#78 Fix broken Google Fonts CSS URL
  CHANGELOG.md
  update-available.html
Labels: area: updates, bug, type: ui

#77 Show current and new versions on update screen
  CHANGELOG.md
  update-available.html
  updater.js
Labels: area: updates, type: ui, type: ux

#76 Create GitHub contribution templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#86 Use new domain for CDN and API
  src/data/Constants.json
  updater.js
Labels: type: backend

#88 Ask community dir
  src/components/HomeTabs/Settings.js
  src/helpers/AddonInstaller/InstallAddon.js
  src/helpers/AddonInstaller/getInstalledAddons.js
  src/helpers/MSFS/Directories/GetPackagesDirectory.js
  src/helpers/MSFS/Directories/ValidateFSDirectory.js
  src/pages/Setup.js
Labels: enhancement, priority: MEDIUM, type: ux

#89 Add VirusTotal scan to automated release CI
  .github/workflows/virusTotal.yml
Labels: type: ci

#104 Allow offline setup
  src/components/App.js
  src/components/MainPage.js
Labels: area: setup, enhancement, priority: LOW, type: ux

#105 Install addon prevent crash
  CHANGELOG.md
  src/components/HomeTabs/AvailableLiveries/AvailableLiveries.js
  src/data/Constants.json
  src/helpers/AddonInstaller/InstallAddon.js
Labels: area: livery installation, priority: HIGH

#106 Update dependencies
  package.json
  yarn.lock
Labels: dependencies, priority: MEDIUM

#107 Installed livery management: uninstallation
  CHANGELOG.md
  package.json
  src/components/FieldValueDisplay.js
  src/components/HomeTabs/AvailableLiveries/AircraftAccordion.js
  src/components/HomeTabs/AvailableLiveries/ListRow.js
  src/components/HomeTabs/InstalledLiveries/AircraftAccordion.js
  src/components/HomeTabs/InstalledLiveries/FullInstalledTable.js
  src/components/HomeTabs/InstalledLiveries/InstalledLiveries.js
  src/components/HomeTabs/InstalledLiveries/ListRow.js
  src/components/HomeTabs/InstalledLiveries/LiveryList.js
  src/helpers/AddonInstaller/deleteAddon.js
  webpack.dev.config.js
  yarn.lock
Labels: area: livery management, area: updates, enhancement, priority: HIGH, type: ux

#117 Bugfixes
  package.json
  src/components/HomeTabs/AvailableLiveries/ListRow.js
  src/data/Constants.json
  src/helpers/verify.js
  updater.js
  yarn.lock
Labels: bug, priority: HIGH

#118 Code optimization
  CHANGELOG.md
  package.json
  src/helpers/AddonInstaller/deleteAddon.js
  src/helpers/AddonInstaller/getInstalledAddons.js
  src/helpers/CleanUp/ClearCache.js
Labels: bug, code improvements, priority: MEDIUM

#119 Use const instead of import
  src/helpers/verify.js
Labels: bug

#136 Refresh installed liveries after install
  CHANGELOG.md
  src/components/HomeTabs/AvailableLiveries/AvailableLiveries.js
  src/components/HomeTabs/InstalledLiveries/InstalledLiveries.js
  src/helpers/AddonInstaller/getInstalledAddons.js
  src/pages/HomePage.js
Labels: area: livery installation, area: livery management, enhancement, priority: HIGH, type: ux

#135 Add Longitude to plane name table
  CHANGELOG.md
  src/data/PlaneNameTable.json
Labels: area: livery installation, bug, priority: MEDIUM

#132 Bump dependencies to latest versions
  package.json
  yarn.lock
Labels: dependencies

#134 Show overlay scrollbars
  CHANGELOG.md
  src/components/MainPage.js
Labels: area: livery installation, enhancement, priority: MEDIUM, type: ui, type: ux

#133 Add button to show community folder in explorer
  CHANGELOG.md
  src/components/HomeTabs/Settings.js
Labels: area: settings, enhancement, priority: LOW

#141 Add delete all liveries button
  CHANGELOG.md
  src/components/HomeTabs/InstalledLiveries/InstalledLiveries.js
Labels: area: livery management, enhancement, priority: LOW, type: ui, type: ux

#140 Clarify liveries refresh box text
  CHANGELOG.md
  src/components/HomeTabs/AvailableLiveries/AvailableLiveries.js
  src/components/HomeTabs/InstalledLiveries/InstalledLiveries.js
  src/components/RefreshBox.js
Labels: enhancement, priority: LOW, type: ux

#142 Update PlaneNameTable.json
  src/data/PlaneNameTable.json
Labels: area: livery installation, area: livery management, bug, priority: HIGH, type: ui, type: ux

#143 Add Sentry.Integrations.RewriteFrames() for sourcemaps
  package.json
  src/helpers/AddonInstaller/InstallAddon.js
  src/helpers/AddonInstaller/deleteAddon.js
  src/helpers/AddonInstaller/getInstalledAddons.js
  src/helpers/Sentry/sentry.js
  yarn.lock
Labels: bug, priority: MEDIUM

#148 Create Community folder if it doesn't exist
  CHANGELOG.md
  src/helpers/MSFS/Directories/GetPackagesDirectory.js
Labels: area: setup, bug, priority: HIGH, type: backend
