Repository MSFS-Mega-Pack/MSFS2020-livery-manager, pull requests merged in 2020-11, with the labels that each got.

#156 Add changelog task to PR template
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: meta, priority: LOW

#155 Allow resizing of manager window
  CHANGELOG.md
  main.js
  src/components/App.js
  src/components/HomeTabs/Feed/Article.js
  src/components/HomeTabs/Settings.js
Labels: enhancement, priority: MEDIUM

#144 Add internationalisation (translation) support
  .babelrc
  .github/ISSUE_TEMPLATE/localisation.md
  CHANGELOG.md
  package.json
  src/components/App.js
  src/components/ContributorBadge.js
  src/components/ErrorDialog.js
  src/components/HomeTabs/AvailableLiveries/AircraftAccordion.js
  src/components/HomeTabs/AvailableLiveries/AvailableLiveries.js
  src/components/HomeTabs/AvailableLiveries/InstalledBadge.js
  src/components/HomeTabs/AvailableLiveries/ListRow.js
  src/components/HomeTabs/AvailableLiveries/UpdateAvailableBadge.js
  src/components/HomeTabs/Feed/Article.js
  src/components/HomeTabs/Feed/Feed.js
  src/components/HomeTabs/InstalledLiveries/AircraftAccordion.js
  src/components/HomeTabs/InstalledLiveries/FullInstalledTable.js
  src/components/HomeTabs/InstalledLiveries/InstalledLiveries.js
  src/components/HomeTabs/InstalledLiveries/ListRow.js
  src/components/HomeTabs/Settings.js
  src/components/MainPage.js
  src/components/MarkdownRenderer.js
  src/components/OfflineError.js
  src/components/RefreshBox.js
  src/data/Theme.js
  src/data/config-keys.json
  src/helpers/AddonInstaller/InstallAddon.js
  src/helpers/AddonInstaller/deleteAddon.js
  src/helpers/Feed/GetActiveFeed.js
  src/helpers/Feed/GetFeedHistory.js
  src/helpers/MSFS/Directories/ValidateFSDirectory.js
  src/helpers/Manifest/FetchAndParseManifest.js
  src/helpers/ShowNativeDialog.js
  src/helpers/verify.js
  src/locales/Locale.js
  src/locales/LocaleContext.js
  src/locales/LocaleHelpers.js
  src/locales/README.md
  src/locales/da-DK/index.js
  src/locales/da-DK/locale.json
  src/locales/en-GB/index.js
  src/locales/en-GB/locale.json
  src/locales/en-US/index.js
  src/locales/en-US/locale.json
  src/locales/index.js
  src/models/Article.js
  src/pages/Setup.js
  src/pages/SplashScreen.js
  webpack.build.config.js
  yarn.lock
Labels: area: settings, enhancement, type: ux

#158 Bonanza added to plane table
  CHANGELOG.md
  src/data/PlaneNameTable.json
Labels: bug, priority: MEDIUM

#159 Fix expand livery tooltip translation
  src/components/HomeTabs/AvailableLiveries/ListRow.js
Labels: bug, internationalisation, priority: MEDIUM

#162 Remove unused Danish locale
  src/locales/da-DK/index.js
  src/locales/da-DK/locale.json
  src/locales/index.js
Labels: internationalisation, priority: LOW

#161 Complete Installed Liveries tab
  CHANGELOG.md
  src/components/FieldValueDisplay.js
  src/components/HomeTabs/AvailableLiveries/AircraftAccordion.js
  src/components/HomeTabs/AvailableLiveries/AvailableLiveries.js
  src/components/HomeTabs/AvailableLiveries/ListRow.js
  src/components/HomeTabs/InstalledLiveries/AircraftAccordion.js
  src/components/HomeTabs/InstalledLiveries/FullInstalledTable.js
  src/components/HomeTabs/InstalledLiveries/InstalledLiveries.js
  src/components/HomeTabs/InstalledLiveries/ListRow.js
  src/components/HomeTabs/InstalledLiveries/LiveryList.js
  src/components/HomeTabs/Settings.js
  src/data/Constants.json
  src/helpers/AddonInstaller/InstallAddon.js
  src/helpers/AddonInstaller/addLiveryInstallAnalytic.js
  src/helpers/GetIndexOfLiveryInArray.js
  src/helpers/Sentry/sentry.js
  src/locales/en-GB/locale.json
  src/locales/en-US/locale.json
Labels: area: livery management, area: updates, priority: HIGH, type: ui, type: ux

#182 Fix locales
  CHANGELOG.md
  src/components/MainPage.js
  src/data/default-config.js
  src/helpers/Sentry/sentry.js
  src/locales/Locale.js
  src/pages/HomePage.js
Labels: bug, internationalisation, priority: HIGH

#180 Added Swedish!
  CHANGELOG.md
  src/locales/index.js
  src/locales/se-SE/index.js
  src/locales/se-SE/locale.json
Labels: internationalisation, priority: MEDIUM

#188 Add dutch language
  CHANGELOG.md
  src/locales/index.js
  src/locales/nl-NL/index.js
  src/locales/nl-NL/locale.json
Labels: internationalisation, priority: MEDIUM
