Repository MSFS-Mega-Pack/MSFS2020-livery-manager, pull requests merged in 2020-08, with the labels that each got.

#3 Fix CI system
  src/data/Routes.js
Labels: bug, type: ci

#5 Use react hot reload, theme improvements
  .babelrc
  package.json
  src/components/App.js
  src/data/Theme.js
  webpack.dev.config.js
  yarn.lock
Labels: dependencies, enhancement

#10 Steam package directory
  src/helpers/MSFS/GetPackagesDirectory.js
Labels: enhancement

#9 Finalise setup stage
  main.js
  package.json
  src/components/ContributorBadge.js
  src/components/LiveryManager/SourceListTable/index.js
  src/data/Routes.js
  src/data/Theme.js
  src/pages/Setup.js
  webpack.build.config.js
  webpack.dev.config.js
  yarn.lock
Labels: enhancement

#12 Fix prettier CI not failing when it should
  .gitattributes
  .github/workflows/node.js.yml
  .prettierrc
  package.json
  src/components/LiveryManager/SourceListTable/index.js
  src/helpers/MSFS/parseCFGFile.js
  src/helpers/Manifest/CFGFileParser.js
Labels: bug, type: ci

#13 Add summary of setup steps at finalisation, add navigate to manager at end of setup
  src/components/LiveryManager/SourceListTable/index.js
  src/data/Theme.js
  src/data/config-keys.json
  src/pages/Setup.js
  src/pages/SplashScreen.js
Labels: area: setup, enhancement

#19 Add ESLint
  .eslintrc.json
  .gitignore
  .vscode/snipsnap.code-snippets
  README.md
  package.json
  src/components/App.js
  src/components/ContributorBadge.js
  src/components/LiveryManager/SourceListTable/index.js
  src/helpers/MSFS/parseCFGFile.js
  src/helpers/Manifest/CFGFileParser.js
  src/helpers/Manifest/FetchAndParseManifest.js
  src/helpers/Manifest/GetLiverySources.js
  src/helpers/Manifest/GetSourceList.js
  src/models/LiverySource.js
  src/models/SourceList.js
  src/pages/LiveryManager.js
  src/pages/Setup.js
  src/pages/SplashScreen.js
  webpack.build.config.js
  yarn.lock
Labels: code improvements

#15 Added: New main dashboard
  package.json
  src/components/MainPage.js
  src/data/Routes.js
  src/pages/LiveryManager.js
  yarn.lock
Labels: area: livery management, enhancement, type: ui

#20 Functions to parse layout.json
  src/helpers/MSFS/index.js
  src/helpers/MSFS/layoutParser.js
  wiki/Errors.md
Labels: area: livery installation, area: livery management, enhancement

#17 CFG Parsing Functions
  src/helpers/MSFS/index.js
  src/helpers/MSFS/parseCFGFile.js
  src/helpers/Manifest/CFGFileParser.js
Labels: area: livery installation, enhancement, type: backend
